### ISSUE TITLE
can not run succesfully after downloading it

### ISSUE THREAD

**Issue by betamoojw** [oliversteiner/lichter-2018#9]
Per readme, I'm trying to run it but it failed. It says below in terminal:
PS D:\lichter-2018> ng serve
An unhandled exception occurred: The D:\lichter-2018\src\environments\environment.staging.ts path in file replacements does not exist.
See "C:\Users\MAXWEL~1\AppData\Local\Temp\ng-ixYV8E\angular-errors.log" for further details.
PS D:\lichter-2018> 

Could you help it? Or better if you can write the instruction on how to run it. Thank you.

**Comment by oliversteiner** [comment]
Hello betamoojw
Thanks for your interest to my project. 
Please try again with the lastest Version from "lichter-2019".
I have it updated to Angular 9 and added some installation words in the readme

**Comment by betamoojw** [comment]
Thanks for your prompt response. Now I've tried the lichter-2019 per the readme instruction and run it sucessfully. I believe we can get this issue closure.
